version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: strapi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  minio:
    image: minio/minio
    container_name: strapi-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    expose:
      - "9000"
      - "9001"
    networks:
      - internal

  strapi:
    image: strapi/strapi:latest
    container_name: strapi
    restart: always
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: ${MYSQL_DATABASE}
      DATABASE_USERNAME: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}

      # Strapi secrets
      APP_KEYS: ${STRAPI_APP_KEYS}
      API_TOKEN_SALT: ${STRAPI_API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${STRAPI_JWT_SECRET}
      JWT_SECRET: ${STRAPI_JWT_SECRET}

      # Minio (для strapi-provider-minio-brokstock)
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_ENDPOINT: minio   # внутри docker-сети сервис называется "minio"
      MINIO_PORT: 9000
      MINIO_USE_SSL: false
      MINIO_HOST: /cdn
    volumes:
      - ./strapi-app:/srv/app
    depends_on:
      - mysql
      - minio
    networks:
      - internal
      - proxy-network

networks:
  internal:
    driver: bridge
  proxy-network:
    external: true

volumes:
  mysql_data:
  minio_data:
