name: Deploy Strapi

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            mkdir -p /opt/apps/strapi
            cd /opt/apps/strapi

            if [ ! -d .git ]; then
              git clone ${{ secrets.REPO_URL }} temp
              mv temp/* temp/.* . 2>/dev/null || true
              rm -rf temp
            fi

            git reset --hard
            git pull origin main

            docker compose down
            docker compose up -d --build
